# Generated by Django 4.0.6 on 2022-07-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_film_magnet_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fav_episode',
            new_name='fav_episodes',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='fav_serial',
            new_name='fav_serials',
        ),
    ]
